### PR TITLE
Some additions

### PR DESCRIPTION
**Pull request by StuntsPT**
Ok, so in short this PR does the following:
1. Remove some redundant `cat` usage from the last 2 sections. I know that the purpose is to show the use of pipes, but this is just bad practice. As it's usually said in ArchLinux forums: "Don't abuse the cat."
2. Add a new section "Working with columns". I wish someone had thought me this a looong time ago, since it is useful in countless situations. This exercise relies heavily on pipes and redirects, so it **might** obsolete the previous `cat | sed`.

Also, this "live command line bootcamp" is **several** degrees of awesome.

### CODE REVIEW

**Comment by blahah** [comment]
Thanks very much for this! Is the PR ready for review?

**Comment by blahah** [comment]
One thing to note is that the tutorial is not currently specific to bioinformatics, and in fact most of the users so far have probably been from other fields.

Working with columns is useful in lots of fields, so I think this PR is valuable. I'm wondering if we can stick to fairly generic data to make it more accessible. How would you feel about switching the VCF for another tab-delimited file, and removing references to bioinformatics?

**Comment by StuntsPT** [comment]
Well spotted.
I'll refactor the vcf file (and the text) to something more generic.
It shouldn't be much work, but I'm especially busy right now. I'll aim for the week after Christmas though.
I'll report here when it's ready.
Cheers.

**Comment by blahah** [comment]
Sounds great - no rush at all, and thanks again for this contribution :)

**Comment by StuntsPT** [comment]
Ok, I droppped the VCF file and changed it to something more "universal" (I was feeling "inspired" today). If not, well, it's still a good way to teach "cut" and "paste"...
Let me know if it looks good, and if you prefer to have me resolve the conflicts or if you prefer to do it yourself (I' not sure what the proper git etiquette is).

**Comment by blahah** [comment]
Thank you for this - much better :). I'm happy for this to be merged.

If you have time to resolve the conflicts that would be excellent - I am swamped for the rest of this week, but otherwise will be able to do it next week.

**Comment by StuntsPT** [comment]
Ok, so it seems that git was able to do a fast-forward... I _think_ everything is ok, but please double check!

Cheers!

**Comment by blahah** [comment]
Whoa, nearly a year since this was ready. I'm so sorry for the long wait, I missed the notification. Merging now - thank you very much for your contributions :)

**Comment by StuntsPT** [comment]
Haha, even I had forgotten about this.
Great to see it was usefull after all!
Cheers.

**Pull request merged**
