### PR TITLE
Update guide.html

### PR DESCRIPTION
**Pull request by gedankenstuecke**
Fixed broken link, otherwise you won't get to the issues :)

### CODE REVIEW

**Comment by blahah** [comment]
Thanks very much @gedankenstuecke!

I'd like you to have this small cactus as a token of my gratitude: :cactus:

**Comment by gedankenstuecke** [comment]
Thanks so much! Just used this this morning as intro to my python course! :+1:

**Comment by blahah** [comment]
Excellent - glad to hear it was useful. Any feedback or ideas for improvement would be very welcome.

**Comment by gedankenstuecke** [comment]
Happy to report any feedback I get, but we really just quickly made our way through the first couple of lessons, hope I can hand it to some more students soon!

**Pull request merged**
